### ISSUE TITLE
Endpoint 'Crear nueva Cuenta'

### ISSUE THREAD

**Issue by juandpr** [ao-libre/ao-api-server#1]
Se solicita el desarrollo de un endpoint en la API para la creacion de una cuenta. Los detalles del endpoints son los siguientes:

```
POST /account
{
    username: 'test@mail.com',
    password: 'password',
}
```

### Restricciones
username: string (32) NO VACIO
password: string (64) NO VACIO

### Acciones
La API generara 2 strings, un `hash` y un `salt`.
El primero tendra una longitud de 32 caracteres, y el segundo, de 10.
Los string seran generados aleatoriamente entre los siguiente caracteres:
```
abcdefghijklmnopqrstuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ
0123456789
#@!~$()-_
```
Una vez que se tengan estos strings, la password sera encriptada usando el algoritmo SHA256 con el salt que generamos.

### Query
La consulta SQL que debera ser ejecutada es la siguiente:
```
INSERT INTO account SET
username = 'TEST@MAIL.COM',
password = 'encryptedPassword',
salt = 'somerandomsalt',
hash = 'somerandomaccounthash',
date_created = NOW(),
date_last_login = NOW();
```

### Posibles respuestas
1) La cuenta ya existe
```
400 Bad Request
{
    error: 'Ya existe esa cuenta'
}
```

2) Falta algun campo requerido
```
400 Bad Request
{
    error: 'Debes completar todos los campos'
}
```

3) Mail invalido
```
400 Bad Request
{
    error: 'el e-mail es invalido'
}
```

### Escenario correcto
```
200 OK
```

**Comment by jormot** [comment]
Por que mejor no usar algo como Auth0?

**Comment by juandpr** [comment]
La base de datos esta creada ya, pero somos abiertos a cambios y mejoras. Si consideras que Auth0 es una mejora, lo puedes implementar
